<a href="https://colab.research.google.com/github/sarvesh238327109/DataScience_Internship/blob/main/DS_Pracrice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 5
m = 6
y = "9"
z = "2"
print(type(x))
print(type(y))
print(x*m)
print(x+m)
print(m-x)
print(y+z)

<class 'int'>
<class 'str'>
30
11
1
92


In [ ]:
#Typecasting
a=int(z)
print(a+m)

8


In [ ]:
#list
l1 = ['hi', 1, 7, 'list', 6.7, 9.5,[3, 59,'hello']]
l2 = l1[6][2]
print(l2)
length = len(l1)
print(length)

hello
7


In [ ]:
# Python program to illustrate a list
# creates an empty list
nums = []

# appending data in list
nums.append(21)
nums.append(10)
nums.append('String')

print(nums)

[21, 10, 'String']


In [ ]:
#Tuple

t1=(1,2,3,4,5,6)
print(t1)

(1, 2, 3, 4, 5, 6)


In [ ]:
#Dictionary

d1={'Name': 'XYZ',
    'Age': 'ABC',
    'Add': 'PQR'}

print(d1)
print(type(d1))
print(d1.keys())
print(d1.items())
print(d1.values())
print(d1['Name'])

{'Name': 'XYZ', 'Age': 'ABC', 'Add': 'PQR'}
<class 'dict'>
dict_keys(['Name', 'Age', 'Add'])
dict_items([('Name', 'XYZ'), ('Age', 'ABC'), ('Add', 'PQR')])
dict_values(['XYZ', 'ABC', 'PQR'])
XYZ


In [ ]:
# accepting integer from the user
# the return type of input() function is string
# so we need to convert the input to integer

num1=int(input("Enter 1st number: "))
num2=int(input("Enter 2nd number: "))

num3 = num1 * num2

print("Product: ", num3)

'''
Python program to illustrate selection statement
'''
num4=int(input("Enter a number"))
if(num4>10):
  print('Number is greater than 10')
elif(num4<10):
  print('Number is less than 10')
else:
  print('Number is equal to 10')

Enter 1st number: 5
Enter 2nd number: 10
Product:  50
Enter a number6
Number is less than 10


In [ ]:
import numpy as np
#In this example, we are creating a two-dimensional array that has the rank of 2 as it has 2 axes.
#The first axis(dimension) is of length 2, i.e., the number of rows, and the second axis(dimension) is of length 3,
#i.e., the number of columns. The overall shape of the array can be represented as (2, 3)
# Creating array object
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [ ]:
import numpy as np

#Creating an array of Rank 1
arr=np.array([1,2,4])
print('Array of Rank 1: ', arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: ", arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple: ", arr)

Array of Rank 1:  [1 2 4]
Array with Rank 2:  [[1 2 3]
 [4 5 6]]

Array created using passed tuple:  [1 3 2]


In [ ]:
import numpy as np

# creating array
arr = np.array([2, 4, 6, 8, 10])

# creating copy of array
c = arr.copy()

# both arr and c have different id
print("id of arr", id(arr))
print("id of c", id(c))

# changing original array
# this will not effect copy
arr[0] = 12

# printing array and copy
print("original array- ", arr)
print("copy- ", c)


id of arr 132486300071856
id of c 132486300270640
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [ ]:
def array_sum(array):
    sum = 0
    for i in array:
        sum += i
    return sum

# Create a test array
testArray = [1, 3, 34, 92, 29, 48, 20.3]

# Test our function
print('The sum of your numbers is ' + str(array_sum(testArray)))


The sum of your numbers is 227.3


In [ ]:
import numpy as np

arr=np.arange(10,1,-2)
print('Updated array = ', arr)

new_arr=a[np.array([3,1,2])]
print('The elements at these indexes are: ', new_arr)

Updated array =  [10  8  6  4  2]
The elements at these indexes are:  [4 8 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

x = arr.copy()
y = arr.view()

arr[0] = 32

print(x)
print(y)

[1 2 3 4 5 6]
[32  2  3  4  5  6]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print(arr.shape)



[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.shape)

newarr = arr.reshape(4,3)

print(newarr)


(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

x = np.array([[1,5],[4,7]])
y = np.array([[6,2],[9,6]])

add = np.add(x,y)
print(add)

sub = np.subtract(x,y)
print(sub)

[[ 7  7]
 [13 13]]
[[-5  3]
 [-5  1]]


In [ ]:
import numpy as np

arr = np.arange(0,20)
print(arr)
newarr = arr.reshape(4,5)
print(newarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
import pandas as pd

myDataSet = {
    'age' : ['23', '43','21'] ,
    'name' : ['X','Y','Z'],
    'dept' : ['HR','Sales','Marketing']
}

df = pd.DataFrame(myDataSet, index=['Row 1', 'Row 2', 'Row 3'])
print(df)

print(type(df))
df.info()

      age name       dept
Row 1  23    X         HR
Row 2  43    Y      Sales
Row 3  21    Z  Marketing
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row 1 to Row 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   age     3 non-null      object
 1   name    3 non-null      object
 2   dept    3 non-null      object
dtypes: object(3)
memory usage: 96.0+ bytes


In [ ]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
import pandas as pd

print(pd.__version__)

2.0.3


In [ ]:
import pandas as pd

data = [1,3,4]

series = pd.Series(data, index=['Row 1','Row 2', 'Row 3'])

print(series)

print(series['Row 2'])

Row 1    1
Row 2    3
Row 3    4
dtype: int64
3


In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

print(df.loc[0])

print(df.loc[[0,1]])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [ ]:
import pandas as pd

df = pd.read_csv('Data.csv')
print(df.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
import pandas as pd

df = pd.read_csv('Data.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
import pandas as pd

df = pd.read_csv('Data.csv')
df.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
import pandas as pd

print(pd.options.display.max_rows)

60


In [ ]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('Data.csv')

print(df)

print(pd.options.display.max_rows)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
9999


In [ ]:
import pandas as pd

data = {
    "Student Name": {
        "0" : "A",
        "1" : "B",
        "2" : "C",
        "3" : "D",
        "4" : "E",
    },
    "Roll No.": {
        "0" : 1,
        "1" : 2,
        "2" : 3,
        "3" : 4,
        "4" : 5,
    },
    "Marks": {
        "0" : 100,
        "1" : 67,
        "2" : 87,
        "3" : 55,
        "4" : 86,
    },
    "Address": {
        "0" : "Borivali",
        "1" : "Andheri",
        "2" : "Vasai",
        "3" : "Naigaon",
        "4" : "Dahisar",
    }
}

df = pd.DataFrame(data)

print(df)

  Student Name  Roll No.  Marks   Address
0            A         1    100  Borivali
1            B         2     67   Andheri
2            C         3     87     Vasai
3            D         4     55   Naigaon
4            E         5     86   Dahisar


In [ ]:
import pandas as pd

df1 = pd.DataFrame({"Fruit": ["banana", "apple", "avocado"],
                    "marketPrice": [23, 45, 54]})
display("First DataFrame")
display(df1)

df2 = pd.DataFrame({"Fruit": ["apple", "banana", "avocado"],
                    "wholesalePrice": [32, 20, 42]})
display("Second DataFrame")
display(df2)

# Merging two dataFrames
display("Merged dataFrame-")
pd.merge(df1, df2, on = "Fruit")

'First DataFrame'

Fruit  marketPrice
0   banana           23
1    apple           45
2  avocado           54

'Second DataFrame'

Fruit  wholesalePrice
0    apple              32
1   banana              20
2  avocado              42

'Merged dataFrame-'

Fruit  marketPrice  wholesalePrice
0   banana           23              20
1    apple           45              32
2  avocado           54              42